[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200

lib_deps =
  arduino-libraries/Arduino_HS300x
  arduino-libraries/Arduino_BMI270_BMM150

build_flags =
  -D BUOY_FW_VERSION=\\"0.1.0\\"

